In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
from pylab import rcParams

%matplotlib inline
rcParams['figure.figsize'] = 15, 10
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_excel("FINAL data - blind test.xls")
df.head()

Resp No  PANEL  CENTRE  MAIN_BRND  AGE  AGES  Plcmnt_Ordr  Prod  Q2A  Q2B  \
0        1      2       1          2   34     2            1     2    7    3   
1        1      2       1          2   34     2            2     3    8    5   
2        1      2       1          2   34     2            3     1    4    5   
3        2      3       1          2   26     1            1     3    7    4   
4        2      3       1          2   26     1            2     1    9    2   

   ...  Q5A_att5  Q5A_att6  Q5A_att7  Q5A_att8  Q5B_att1  Q5B_att2  Q5B_att3  \
0  ...         7         7         7         7         3         4         4   
1  ...         8         7         8         8         5         5         5   
2  ...         7         7         6         7         5         5         3   
3  ...         7         8        10         8         3         3         3   
4  ...         9        10        10         9         3         3         4   

   Q5B_att4  Q5B_att5  Q6_Int_p (Y=1,N=2)  
0         4         3                   2  
1         5         3                   2  
2         5         5                   2  
3         3         3                   1  
4         4         3                   1  

[5 rows x 26 columns]

In [3]:
df.columns

Index(['Resp No', 'PANEL', 'CENTRE', 'MAIN_BRND', 'AGE', 'AGES', 'Plcmnt_Ordr',
       'Prod', 'Q2A', 'Q2B', 'Q3A', 'Q3B', 'Q5A_att1', 'Q5A_att2', 'Q5A_att3',
       'Q5A_att4', 'Q5A_att5', 'Q5A_att6', 'Q5A_att7', 'Q5A_att8', 'Q5B_att1',
       'Q5B_att2', 'Q5B_att3', 'Q5B_att4', 'Q5B_att5', 'Q6_Int_p (Y=1,N=2)'],
      dtype='object')

In [4]:
data=df.loc[:,('Q5A_att1', 'Q5A_att2', 'Q5A_att3',
       'Q5A_att4', 'Q5A_att5', 'Q5A_att6', 'Q5A_att7', 'Q5A_att8')]
data.head()

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att7  \
0         7         6         7         7         7         7         7   
1         8         8         8         8         8         7         8   
2         7         6         7         8         7         7         6   
3        10         8         8         8         7         8        10   
4         9         9         9         9         9        10        10   

   Q5A_att8  
0         7  
1         8  
2         7  
3         8  
4         9

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2280 entries, 0 to 2279
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Q5A_att1  2280 non-null   int64
 1   Q5A_att2  2280 non-null   int64
 2   Q5A_att3  2280 non-null   int64
 3   Q5A_att4  2280 non-null   int64
 4   Q5A_att5  2280 non-null   int64
 5   Q5A_att6  2280 non-null   int64
 6   Q5A_att7  2280 non-null   int64
 7   Q5A_att8  2280 non-null   int64
dtypes: int64(8)
memory usage: 142.6 KB


In [6]:
X=data.loc[:,('Q5A_att2', 'Q5A_att3',
       'Q5A_att4', 'Q5A_att5', 'Q5A_att6', 'Q5A_att7', 'Q5A_att8')]
X

Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att7  Q5A_att8
0            6         7         7         7         7         7         7
1            8         8         8         8         7         8         8
2            6         7         8         7         7         6         7
3            8         8         8         7         8        10         8
4            9         9         9         9        10        10         9
...        ...       ...       ...       ...       ...       ...       ...
2275         7         7         8         7         8         7         9
2276         4         4         4         4         4         4         4
2277         7         7         6         6         6         6         6
2278         7         7         7         6         6         6         6
2279         4         4         4         4         4         4         4

[2280 rows x 7 columns]

In [7]:
y=data.loc[:,"Q5A_att1"]
y

0        7
1        8
2        7
3       10
4        9
        ..
2275     8
2276     4
2277     9
2278     8
2279     4
Name: Q5A_att1, Length: 2280, dtype: int64

In [8]:
import statsmodels.api as sm
def regression_results(x,y):
    x=sm.add_constant(x)
    model=sm.OLS(y,x).fit()
    print(model.summary())

In [9]:
regression_results(X,y)

                            OLS Regression Results                            
Dep. Variable:               Q5A_att1   R-squared:                       0.775
Model:                            OLS   Adj. R-squared:                  0.774
Method:                 Least Squares   F-statistic:                     1117.
Date:                Tue, 07 Jun 2022   Prob (F-statistic):               0.00
Time:                        23:20:46   Log-Likelihood:                -2736.5
No. Observations:                2280   AIC:                             5489.
Df Residuals:                    2272   BIC:                             5535.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5755      0.082      7.042      0.0

# Without Q5A_att7

In [10]:
X=data.loc[:,('Q5A_att2', 'Q5A_att3',
       'Q5A_att4', 'Q5A_att5', 'Q5A_att6', 'Q5A_att8')]
X

Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att8
0            6         7         7         7         7         7
1            8         8         8         8         7         8
2            6         7         8         7         7         7
3            8         8         8         7         8         8
4            9         9         9         9        10         9
...        ...       ...       ...       ...       ...       ...
2275         7         7         8         7         8         9
2276         4         4         4         4         4         4
2277         7         7         6         6         6         6
2278         7         7         7         6         6         6
2279         4         4         4         4         4         4

[2280 rows x 6 columns]

In [11]:
regression_results(X,y)

                            OLS Regression Results                            
Dep. Variable:               Q5A_att1   R-squared:                       0.775
Model:                            OLS   Adj. R-squared:                  0.774
Method:                 Least Squares   F-statistic:                     1302.
Date:                Tue, 07 Jun 2022   Prob (F-statistic):               0.00
Time:                        23:20:47   Log-Likelihood:                -2738.0
No. Observations:                2280   AIC:                             5490.
Df Residuals:                    2273   BIC:                             5530.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5892      0.081      7.241      0.0

In [12]:
data1=data.drop("Q5A_att7",axis=1)
data1

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att8
0            7         6         7         7         7         7         7
1            8         8         8         8         8         7         8
2            7         6         7         8         7         7         7
3           10         8         8         8         7         8         8
4            9         9         9         9         9        10         9
...        ...       ...       ...       ...       ...       ...       ...
2275         8         7         7         8         7         8         9
2276         4         4         4         4         4         4         4
2277         9         7         7         6         6         6         6
2278         8         7         7         7         6         6         6
2279         4         4         4         4         4         4         4

[2280 rows x 7 columns]

In [46]:
data3=data.apply(stats.zscore)
data3

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att7  \
0    -0.350115 -0.781965 -0.301486 -0.257176 -0.229424 -0.232727 -0.303240   
1     0.240316  0.304826  0.264732  0.292882  0.324107 -0.232727  0.266271   
2    -0.350115 -0.781965 -0.301486  0.292882 -0.229424 -0.232727 -0.872751   
3     1.421177  0.304826  0.264732  0.292882 -0.229424  0.314301  1.405294   
4     0.830746  0.848221  0.830950  0.842940  0.877639  1.408356  1.405294   
...        ...       ...       ...       ...       ...       ...       ...   
2275  0.240316 -0.238570 -0.301486  0.292882 -0.229424  0.314301 -0.303240   
2276 -2.121407 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.011773   
2277  0.830746 -0.238570 -0.301486 -0.807234 -0.782956 -0.779754 -0.872751   
2278  0.240316 -0.238570 -0.301486 -0.257176 -0.782956 -0.779754 -0.872751   
2279 -2.121407 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.011773   

      Q5A_att8  
0    -0.288764  
1     0.285240  
2    -0.288764  
3     0.285240  
4     0.859244  
...        ...  
2275  0.859244  
2276 -2.010777  
2277 -0.862769  
2278 -0.862769  
2279 -2.010777  

[2280 rows x 8 columns]

In [13]:
from scipy import stats

# standardizing dataframe
data2=data1.apply(stats.zscore)
data2.head()

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att8
0 -0.350115 -0.781965 -0.301486 -0.257176 -0.229424 -0.232727 -0.288764
1  0.240316  0.304826  0.264732  0.292882  0.324107 -0.232727  0.285240
2 -0.350115 -0.781965 -0.301486  0.292882 -0.229424 -0.232727 -0.288764
3  1.421177  0.304826  0.264732  0.292882 -0.229424  0.314301  0.285240
4  0.830746  0.848221  0.830950  0.842940  0.877639  1.408356  0.859244

In [14]:
X_standard=data2.loc[:,('Q5A_att2', 'Q5A_att3',
       'Q5A_att4', 'Q5A_att5', 'Q5A_att6', 'Q5A_att8')]

In [15]:
y_standard=data2.iloc[:,0]

In [16]:
model=sm.OLS(y_standard,X_standard).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:               Q5A_att1   R-squared (uncentered):                   0.775
Model:                            OLS   Adj. R-squared (uncentered):              0.774
Method:                 Least Squares   F-statistic:                              1303.
Date:                Tue, 07 Jun 2022   Prob (F-statistic):                        0.00
Time:                        23:20:53   Log-Likelihood:                         -1536.7
No. Observations:                2280   AIC:                                      3085.
Df Residuals:                    2274   BIC:                                      3120.
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [17]:
0.1743+0.3003+0.1183+0.0890+0.1011+0.2062

0.9891999999999999

# RFE

In [18]:
from sklearn.feature_selection import RFE

In [19]:
data1

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att8
0            7         6         7         7         7         7         7
1            8         8         8         8         8         7         8
2            7         6         7         8         7         7         7
3           10         8         8         8         7         8         8
4            9         9         9         9         9        10         9
...        ...       ...       ...       ...       ...       ...       ...
2275         8         7         7         8         7         8         9
2276         4         4         4         4         4         4         4
2277         9         7         7         6         6         6         6
2278         8         7         7         7         6         6         6
2279         4         4         4         4         4         4         4

[2280 rows x 7 columns]

In [20]:
X=data1.drop("Q5A_att1",axis=1)
y=data1["Q5A_att1"]

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
for i in range(1,X.shape[1]+1):
    lr=LinearRegression()
    selector = RFE(lr,n_features_to_select=i,step=1)
    print(i)
    selector.fit(X,y)
    print(selector.score(X,y))

1
0.6788478344365869
2
0.7352557067105396
3
0.7599410101347628
4
0.7688451631108097
5
0.7723149751268881
6
0.7746132901891931


# Correlation

In [23]:
data.corr()

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  \
Q5A_att1  1.000000  0.723069  0.823922  0.766472  0.765972  0.765213   
Q5A_att2  0.723069  1.000000  0.699165  0.650235  0.699211  0.644325   
Q5A_att3  0.823922  0.699165  1.000000  0.777731  0.783251  0.749416   
Q5A_att4  0.766472  0.650235  0.777731  1.000000  0.730227  0.783715   
Q5A_att5  0.765972  0.699211  0.783251  0.730227  1.000000  0.742777   
Q5A_att6  0.765213  0.644325  0.749416  0.783715  0.742777  1.000000   
Q5A_att7  0.770606  0.658032  0.790696  0.758622  0.772320  0.795996   
Q5A_att8  0.799983  0.652336  0.796745  0.761744  0.768208  0.814465   

          Q5A_att7  Q5A_att8  
Q5A_att1  0.770606  0.799983  
Q5A_att2  0.658032  0.652336  
Q5A_att3  0.790696  0.796745  
Q5A_att4  0.758622  0.761744  
Q5A_att5  0.772320  0.768208  
Q5A_att6  0.795996  0.814465  
Q5A_att7  1.000000  0.830628  
Q5A_att8  0.830628  1.000000

# PCA

In [24]:
data2

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att8
0    -0.350115 -0.781965 -0.301486 -0.257176 -0.229424 -0.232727 -0.288764
1     0.240316  0.304826  0.264732  0.292882  0.324107 -0.232727  0.285240
2    -0.350115 -0.781965 -0.301486  0.292882 -0.229424 -0.232727 -0.288764
3     1.421177  0.304826  0.264732  0.292882 -0.229424  0.314301  0.285240
4     0.830746  0.848221  0.830950  0.842940  0.877639  1.408356  0.859244
...        ...       ...       ...       ...       ...       ...       ...
2275  0.240316 -0.238570 -0.301486  0.292882 -0.229424  0.314301  0.859244
2276 -2.121407 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.010777
2277  0.830746 -0.238570 -0.301486 -0.807234 -0.782956 -0.779754 -0.862769
2278  0.240316 -0.238570 -0.301486 -0.257176 -0.782956 -0.779754 -0.862769
2279 -2.121407 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.010777

[2280 rows x 7 columns]

In [47]:
data3

Q5A_att1  Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att7  \
0    -0.350115 -0.781965 -0.301486 -0.257176 -0.229424 -0.232727 -0.303240   
1     0.240316  0.304826  0.264732  0.292882  0.324107 -0.232727  0.266271   
2    -0.350115 -0.781965 -0.301486  0.292882 -0.229424 -0.232727 -0.872751   
3     1.421177  0.304826  0.264732  0.292882 -0.229424  0.314301  1.405294   
4     0.830746  0.848221  0.830950  0.842940  0.877639  1.408356  1.405294   
...        ...       ...       ...       ...       ...       ...       ...   
2275  0.240316 -0.238570 -0.301486  0.292882 -0.229424  0.314301 -0.303240   
2276 -2.121407 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.011773   
2277  0.830746 -0.238570 -0.301486 -0.807234 -0.782956 -0.779754 -0.872751   
2278  0.240316 -0.238570 -0.301486 -0.257176 -0.782956 -0.779754 -0.872751   
2279 -2.121407 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.011773   

      Q5A_att8  
0    -0.288764  
1     0.285240  
2    -0.288764  
3     0.285240  
4     0.859244  
...        ...  
2275  0.859244  
2276 -2.010777  
2277 -0.862769  
2278 -0.862769  
2279 -2.010777  

[2280 rows x 8 columns]

In [48]:
X_pca=data3.iloc[:,1:]
X_pca

Q5A_att2  Q5A_att3  Q5A_att4  Q5A_att5  Q5A_att6  Q5A_att7  Q5A_att8
0    -0.781965 -0.301486 -0.257176 -0.229424 -0.232727 -0.303240 -0.288764
1     0.304826  0.264732  0.292882  0.324107 -0.232727  0.266271  0.285240
2    -0.781965 -0.301486  0.292882 -0.229424 -0.232727 -0.872751 -0.288764
3     0.304826  0.264732  0.292882 -0.229424  0.314301  1.405294  0.285240
4     0.848221  0.830950  0.842940  0.877639  1.408356  1.405294  0.859244
...        ...       ...       ...       ...       ...       ...       ...
2275 -0.238570 -0.301486  0.292882 -0.229424  0.314301 -0.303240  0.859244
2276 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.011773 -2.010777
2277 -0.238570 -0.301486 -0.807234 -0.782956 -0.779754 -0.872751 -0.862769
2278 -0.238570 -0.301486 -0.257176 -0.782956 -0.779754 -0.872751 -0.862769
2279 -1.868755 -2.000141 -1.907351 -1.890019 -1.873809 -2.011773 -2.010777

[2280 rows x 7 columns]

In [26]:
from sklearn.decomposition import PCA 

In [36]:
pca = PCA(n_components=5)

In [49]:
inp=pca.fit_transform(X_pca)
inp

array([[ 8.87055039e-01,  4.65339286e-01,  9.58851273e-02,
        -1.56038124e-01, -1.06431408e-01],
       [-5.65220080e-01, -2.04214941e-01,  1.37310765e-01,
        -2.38493692e-01,  1.46586982e-01],
       [ 9.00378963e-01,  4.36403233e-01, -4.33586038e-01,
        -5.42759359e-01, -3.21796194e-01],
       ...,
       [ 1.77110056e+00, -4.57392285e-01, -4.18902722e-02,
        -1.23537598e-01,  2.66239189e-01],
       [ 1.56371943e+00, -3.62638147e-01, -4.19962973e-01,
        -3.69358647e-01,  2.05738624e-01],
       [ 5.12638714e+00,  1.10273461e-01, -2.48652582e-03,
        -2.56838422e-02, -9.86836508e-02]])

In [50]:
inp_df=pd.DataFrame(inp)
inp_df

0         1         2         3         4
0     0.887055  0.465339  0.095885 -0.156038 -0.106431
1    -0.565220 -0.204215  0.137311 -0.238494  0.146587
2     0.900379  0.436403 -0.433586 -0.542759 -0.321796
3    -1.005782  0.280622 -0.007703  0.483494  0.616515
4    -2.679122  0.203479 -0.016058  0.415319 -0.091785
...        ...       ...       ...       ...       ...
2275 -0.161903  0.549908 -0.316241  0.346891 -0.053982
2276  5.126387  0.110273 -0.002487 -0.025684 -0.098684
2277  1.771101 -0.457392 -0.041890 -0.123538  0.266239
2278  1.563719 -0.362638 -0.419963 -0.369359  0.205739
2279  5.126387  0.110273 -0.002487 -0.025684 -0.098684

[2280 rows x 5 columns]

In [51]:
y_pca=data3.iloc[:,0]
y_pca

0      -0.350115
1       0.240316
2      -0.350115
3       1.421177
4       0.830746
          ...   
2275    0.240316
2276   -2.121407
2277    0.830746
2278    0.240316
2279   -2.121407
Name: Q5A_att1, Length: 2280, dtype: float64

In [52]:
regression_results(inp_df,y_pca)

                            OLS Regression Results                            
Dep. Variable:               Q5A_att1   R-squared:                       0.771
Model:                            OLS   Adj. R-squared:                  0.771
Method:                 Least Squares   F-statistic:                     1532.
Date:                Tue, 07 Jun 2022   Prob (F-statistic):               0.00
Time:                        23:41:23   Log-Likelihood:                -1554.1
No. Observations:                2280   AIC:                             3120.
Df Residuals:                    2274   BIC:                             3155.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.365e-16      0.010   3.35e-14      1.0

In [53]:
loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
loadings

array([[-0.80221457, -0.56798521, -0.10319053,  0.1473986 ,  0.03471065],
       [-0.9051125 , -0.02429232,  0.06766965, -0.24547725,  0.25128392],
       [-0.88293997,  0.11310771, -0.36099729, -0.22448632, -0.0516285 ],
       [-0.8879226 , -0.09049449,  0.28164088, -0.17113268, -0.30716547],
       [-0.89484808,  0.19345055, -0.14496456,  0.23104282, -0.17335337],
       [-0.90757098,  0.1426053 ,  0.13962284,  0.12427643,  0.12764022],
       [-0.91068384,  0.17084392,  0.10234019,  0.14775912,  0.11235598]])

In [54]:
pca.explained_variance_

array([5.48454962, 0.43112695, 0.27585087, 0.2523241 , 0.22033185])

In [59]:
pca.components_

array([[-0.34254692, -0.3864845 , -0.37701679, -0.37914438, -0.38210157,
        -0.38753427, -0.38886347],
       [-0.86503651, -0.036997  ,  0.17226206, -0.13782232,  0.29462349,
         0.21718663,  0.26019379],
       [-0.1964729 ,  0.12884179, -0.68733232,  0.53623914, -0.2760099 ,
         0.26583937,  0.19485387],
       [ 0.29343641, -0.48868823, -0.44690016, -0.34068545,  0.45995263,
         0.24740552,  0.29415411],
       [ 0.07394761,  0.53533552, -0.10998941, -0.65438562, -0.36931219,
         0.27192487,  0.23936331]])

In [60]:
np.sum(loadings**2,axis=0)

array([5.48454962, 0.43112695, 0.27585087, 0.2523241 , 0.22033185])